### ISSUE TITLE
Repurposing otr4j organization for OTRv4 implementation in otr4j

### ISSUE THREAD

**Issue by cobratbq** [otr4j/otr4j-issues#23]
Hi all, I would like to "repurpose" the 'otr4j' organization to host my recent progress on implementing [OTRv4](https://github.com/otrv4/otrv4) in otr4j. My work is currently available at https://github.com/cobratbq/otr4j and is a work-in-progress but with sufficient basics already implemented that it works for otr4j-to-otr4j conversations.

I'd like to use the 'otr4j' organization such that we can keep the number of "otr4j" repositories low. This will avoid confusion and keeps things predictable.

Please let me know if you'll bless the initiative to host it in this github organization. (It's basically a continuation of this repository anyways.) Also, please let me know if you feel like reviewing lots of new and changed code :-)

**Comment by eighthave** [comment]
yes!  Please do!  Its great that you're doing this work.  I'm not
working on secure messenging at all these days, so I don't have much to
add in reviews, etc.  But I'm very happy to see progress on this.

Seems like I should actually entirely hand over the github org to you
@cobratbq

**Comment by cobratbq** [comment]
Okay. I'll give it a few days for @n8fr8 and possibly @devrandom to respond. Then I'll start using the organization. Thanks for your support! @a-iv, thanks for taking the effort to give your okay.
